### ISSUE TITLE
关于LoadingMore

### ISSUE THREAD

**Issue by xiaohao890809** [IvorHu/RealStuff#11]
每次fetched的个数不一样呢，
List<String> dates = DateUtil.generateSequenceDateBefore(publishedAt, 10);
按照上面的获取方法，不是每个下拉更新数据的时候是十个吗，为啥每次获取到的更新数据条数会不一样呢，跟网络有关吗？谢谢！

**Comment by IvorHu** [comment]
对，就是不一样。因为获取数据是根据日期获取的，节假日是没有数据更新的，而且每天获取的各类数据数量也不同（比如iOS和Android可能是每天5条，而其他的可能是每天一条）。你贴的代码是生成之前连续十天的日期List。

**Comment by xiaohao890809** [comment]
嗯嗯，瞬间明白了，谢谢您的答疑解惑。
