### ISSUE TITLE
dev版本发现一个bug

### ISSUE THREAD

**Issue by xiaohao890809** [IvorHu/RealStuff#12]
先去每个子页面多收藏几个item，结果去收藏里点取消收藏的时候，有时候点击取消的时候item并没有消失，要刷新一下才会更新一下。之前的版本是正常的。
备注：测试机型是小米5，安卓6.0

**Comment by IvorHu** [comment]
我还没有碰过这情况，出现的频率高吗？可以复现吗？之前有哪些操作？

**Comment by xiaohao890809** [comment]
恩，可以复现的，之前的操作是去收藏文章，然后去收藏里点击取消收藏。
频率蛮高的

**Comment by IvorHu** [comment]
怎么复现，之前有哪些操作？

**Comment by xiaohao890809** [comment]
1.进入app
2.随便进入几个标签，收藏5-6篇文章
3.去收藏里面，从上往下点击取消收藏

**Comment by xiaohao890809** [comment]
请问您的可以复现吗？

**Comment by IvorHu** [comment]
可以，我在我手机上复现了，不过在虚拟机里没有。而且发现如果取消了一个收藏，没动画，再取消一个，有可能会同时出现两个动画。我正在修复。

**Comment by IvorHu** [comment]
@xiaohao890809 问题已修复。
