### ISSUE TITLE
关于RecycleView+Glide实现瀑布流重新排列的问题

### ISSUE THREAD

**Issue by Creep0824** [IvorHu/RealStuff#15]
你好，一直在学习你的项目，遇到问题想请教一下，我用recyclerview+glide写瀑布流，图片会出现疑似复用的问题，滑动过程中尺寸不停的在变化，位置也发生改变，这个该怎么解决呢？盼大神回复

**Comment by IvorHu** [comment]
你说的这个问题应该已经修复了，试下最新的master分支，只有顶部的图片会有位置变化。不知道你说的是不是这个问题？

**Comment by IvorHu** [comment]
@MarshallMathersIII 不知道你的问题解决了吗？我暂时关了这个issue，有需要的话你再打开吧。
