### ISSUE TITLE
IvoeHu，您好

### ISSUE THREAD

**Issue by xiaohao890809** [IvorHu/RealStuff#16]
请问下，您的项目里用到的 Realm 缓存的数据里之前的数据都是不变的，现在我的一个项目里，之前的数据会变，如果之前保存在Realm里面了，每次重新加载的时候，怎么把之前的数据更新重新显示呢？（除了清除缓存外），谢谢

**Comment by IvorHu** [comment]
@xiaohao890809 项目里的Realm数据是会变的，比如收藏了一个干货，这个干货对应的数据就变了。另外，Realm是支持查询自动更新的。

**Comment by xiaohao890809** [comment]
嗯嗯，谢谢
