### ISSUE TITLE
请问在搜索结果中可以显示已收藏的图标效果吗？

### ISSUE THREAD

**Issue by xiaohao890809** [IvorHu/RealStuff#17]
请问在搜索结果中的 item 可以显示已收藏的图标效果吗？意思就是说如果之前搜索了一个关键字，在搜索结果中点击了收藏，下次再搜索时这个结果显示已被收藏。
我试了下：
holder.likeBtn.setImageResource(searchBean.isLiked()?R.mipmap.like:R.mipmap.unlike);
这样子还是不行呢？求助。

**Comment by IvorHu** [comment]
由于搜索和干货API返回的json字段不是完全一致，所以搜索结果需要包装成普通干货。
