### ISSUE TITLE
关于下拉刷新的bug反馈

### ISSUE THREAD

**Issue by ghost** [IvorHu/RealStuff#19]
每当第二天gank.io更新后，app中无法通过下拉刷新获取最新内容。必须手动清空相应抽屉的缓存之后，才能通过下拉刷新重新加载，获取最新内容。
复现环境：
app装入手机后不能再连接电脑调试。因为连接电脑调试后，手机中的app会被删除并安装新的app，此时该app会第一次获取最新的gank.io的内容。

**Comment by DomceyKoo** [comment]
每当第二天gank.io更新后，app中无法通过下拉刷新获取最新内容。必须手动清空相应抽屉的缓存之后，才能通过下拉刷新重新加载，获取最新内容。
复现环境：
app装入手机后不能再连接电脑调试。因为连接电脑调试后，手机中的app会被删除并安装新的app，此时该app会第一次获取最新的gank.io的内容。

**Comment by ghost** [comment]
解决了！谢谢 Ivor ~
