### ISSUE TITLE
关于APP板块以及扩展资源板块的问题

### ISSUE THREAD

**Issue by ghost** [IvorHu/RealStuff#20]
APP板块上拉加载，最多只能加载到2016/5/20号的内容，扩展资源只能加载到2016/7/26。这是为什么呢？难道是gank.io的api在这两个日期之前是不一样的吗？希望Ivor能够帮我解惑。
其他板块都能加载很多，不能确定是否有上述问题。
另外，那个点击图片查看的动画issue我觉得Ivor可以close了，:-P

**Comment by IvorHu** [comment]
这是多方面的原因。一是gank提供的数据并不是每天都有APP类别的数据；二是我程序处理的不是很完善，目前的加载是以目前最早干货的日期为基准，获取之前10天的数据，如果之前10天的数据中没有APP类别的数据，就提示没有更多了。所以综上，估计是2016/5/19至2016/5/9这几天都没有APP的数据，但是并不是意味着2016/5/9之前也没有APP的数据，我在这方面处理的简单了。

**Comment by ghost** [comment]
我也尝试着去修复这个问题，发现实在是我力所不能及的，=￣ω￣=，然后经过你一分析，我就释然了。另外，拓展资源这块是怎么解析的啊。我发现，7.26前面一两天就有数据的啊，那这是什么原因呢。

**Comment by IvorHu** [comment]
API请求都是用retrofit完成的，这个问题我也不清除。我再看看吧
