### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by sunreview** [IvorHu/RealStuff#25]
我正在看你的项目，有些不懂的。能否有偿向你提问下呢？有偿，谢谢！

**Comment by IvorHu** [comment]
> 我正在看你的项目，有些不懂的。能否有偿向你提问下呢？有偿，谢谢！

有什么问题就问吧

**Comment by sunreview** [comment]
`
public class DateConverter {
    @TypeConverter
    public static Date toDate(Long timestamp) {
        return timestamp == null ? null : new Date(timestamp);
    }

    @TypeConverter
    public static Long toTimestamp(Date date) {
        return date == null ? null : date.getTime();
    }
}

`
这段代码的作用应该就是 Date和long之间的互转，其中@TypeConverter 这个注解什么作用呢，谢谢

**Comment by tomridder** [comment]
``
public class DateConverter {
@TypeConverter
public static Date toDate(Long timestamp) {
return timestamp == null ? null : new Date(timestamp);
}

@TypeConverter
public static Long toTimestamp(Date date) {
    return date == null ? null : date.getTime();
}
}
``

**Comment by tomridder** [comment]
'''
public class DateConverter {
@TypeConverter
public static Date toDate(Long timestamp) {
return timestamp == null ? null : new Date(timestamp);
}

@TypeConverter
public static Long toTimestamp(Date date) {
    return date == null ? null : date.getTime();
}
}
'''

**Comment by tomridder** [comment]
`public class DateConverter {
@TypeConverter
public static Date toDate(Long timestamp) {
return timestamp == null ? null : new Date(timestamp);
}

@TypeConverter
public static Long toTimestamp(Date date) {
    return date == null ? null : date.getTime();
}
}`

**Comment by sunreview** [comment]
少侠，回答下我的问题啊

**Comment by IvorHu** [comment]
> 少侠，回答下我的问题啊

https://developer.android.google.cn/reference/android/arch/persistence/room/TypeConverter.html
