### ISSUE TITLE
关于图片的点击问题

### ISSUE THREAD

**Issue by AndroidLi123** [IvorHu/RealStuff#8]
为什么我也用这个 ActivityOptionsCompat.makeSceneTransitionAnimation有时会出现点击图片时，刚开始缩小后放大的情况。

**Comment by IvorHu** [comment]
我不清楚这种情况，也没遇到过。建议查下官方文档。

**Comment by IvorHu** [comment]
@416679828 会不会是你设置的图片大小是偏小的，所以动画前先缩小。
